[pytest]
testpaths = tests
markers =
    performance: marks performance-oriented tests.
filterwarnings =
    ignore:pkg_resources is deprecated as an API:DeprecationWarning
    ignore:Deprecated call to .*declare_namespace.*:DeprecationWarning
